# Generated by Django 2.2.3 on 2019-07-30 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailValidLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tb_email_valid_log',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('gender', models.CharField(choices=[(1, '男'), (0, '女')], max_length=2)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('tel', models.CharField(max_length=20, null=True, unique=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
    ]
