# Generated by Django 2.2.3 on 2019-08-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='emailvalidlog',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
