# Generated by Django 2.2.3 on 2019-08-01 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190801_0824'),
        ('blog', '0002_auto_20190801_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
